FROM golang:1.25.4-alpine AS builder

RUN go install github.com/swaggo/swag/cmd/swag@latest

WORKDIR /app

COPY go.mod go.sum ./

RUN go mod download

COPY . .
RUN cat config/prod.config.yaml > config/config.yaml

RUN swag init -g cmd/api/main.go

RUN go build -o main cmd/api/main.go

FROM alpine:latest as runner

ENV GO_ENV=production

WORKDIR /app

COPY --from=builder /app/main .
COPY --from=builder /app/config/config.yaml .
COPY --from=builder /app/docs .

EXPOSE 8080

CMD ["./main"]
