// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockSender creates a new instance of MockSender. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSender(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSender {
	mock := &MockSender{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockSender is an autogenerated mock type for the Sender type
type MockSender struct {
	mock.Mock
}

type MockSender_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSender) EXPECT() *MockSender_Expecter {
	return &MockSender_Expecter{mock: &_m.Mock}
}

// IsStarted provides a mock function for the type MockSender
func (_mock *MockSender) IsStarted() bool {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for IsStarted")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func() bool); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MockSender_IsStarted_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsStarted'
type MockSender_IsStarted_Call struct {
	*mock.Call
}

// IsStarted is a helper method to define mock.On call
func (_e *MockSender_Expecter) IsStarted() *MockSender_IsStarted_Call {
	return &MockSender_IsStarted_Call{Call: _e.mock.On("IsStarted")}
}

func (_c *MockSender_IsStarted_Call) Run(run func()) *MockSender_IsStarted_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockSender_IsStarted_Call) Return(b bool) *MockSender_IsStarted_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *MockSender_IsStarted_Call) RunAndReturn(run func() bool) *MockSender_IsStarted_Call {
	_c.Call.Return(run)
	return _c
}

// Start provides a mock function for the type MockSender
func (_mock *MockSender) Start() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Start")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockSender_Start_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Start'
type MockSender_Start_Call struct {
	*mock.Call
}

// Start is a helper method to define mock.On call
func (_e *MockSender_Expecter) Start() *MockSender_Start_Call {
	return &MockSender_Start_Call{Call: _e.mock.On("Start")}
}

func (_c *MockSender_Start_Call) Run(run func()) *MockSender_Start_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockSender_Start_Call) Return(err error) *MockSender_Start_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockSender_Start_Call) RunAndReturn(run func() error) *MockSender_Start_Call {
	_c.Call.Return(run)
	return _c
}

// Stop provides a mock function for the type MockSender
func (_mock *MockSender) Stop() {
	_mock.Called()
	return
}

// MockSender_Stop_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Stop'
type MockSender_Stop_Call struct {
	*mock.Call
}

// Stop is a helper method to define mock.On call
func (_e *MockSender_Expecter) Stop() *MockSender_Stop_Call {
	return &MockSender_Stop_Call{Call: _e.mock.On("Stop")}
}

func (_c *MockSender_Stop_Call) Run(run func()) *MockSender_Stop_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockSender_Stop_Call) Return() *MockSender_Stop_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockSender_Stop_Call) RunAndReturn(run func()) *MockSender_Stop_Call {
	_c.Run(run)
	return _c
}
