// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocksrepository

import (
	"context"
	"insider/internal/model"

	mock "github.com/stretchr/testify/mock"
)

// NewMockMessageRepository creates a new instance of MockMessageRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockMessageRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockMessageRepository {
	mock := &MockMessageRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockMessageRepository is an autogenerated mock type for the MessageRepository type
type MockMessageRepository struct {
	mock.Mock
}

type MockMessageRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockMessageRepository) EXPECT() *MockMessageRepository_Expecter {
	return &MockMessageRepository_Expecter{mock: &_m.Mock}
}

// Count provides a mock function for the type MockMessageRepository
func (_mock *MockMessageRepository) Count(ctx context.Context, r *model.ListMessagesRequest) (*int64, error) {
	ret := _mock.Called(ctx, r)

	if len(ret) == 0 {
		panic("no return value specified for Count")
	}

	var r0 *int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *model.ListMessagesRequest) (*int64, error)); ok {
		return returnFunc(ctx, r)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *model.ListMessagesRequest) *int64); ok {
		r0 = returnFunc(ctx, r)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*int64)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *model.ListMessagesRequest) error); ok {
		r1 = returnFunc(ctx, r)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockMessageRepository_Count_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Count'
type MockMessageRepository_Count_Call struct {
	*mock.Call
}

// Count is a helper method to define mock.On call
//   - ctx context.Context
//   - r *model.ListMessagesRequest
func (_e *MockMessageRepository_Expecter) Count(ctx interface{}, r interface{}) *MockMessageRepository_Count_Call {
	return &MockMessageRepository_Count_Call{Call: _e.mock.On("Count", ctx, r)}
}

func (_c *MockMessageRepository_Count_Call) Run(run func(ctx context.Context, r *model.ListMessagesRequest)) *MockMessageRepository_Count_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *model.ListMessagesRequest
		if args[1] != nil {
			arg1 = args[1].(*model.ListMessagesRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockMessageRepository_Count_Call) Return(n *int64, err error) *MockMessageRepository_Count_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockMessageRepository_Count_Call) RunAndReturn(run func(ctx context.Context, r *model.ListMessagesRequest) (*int64, error)) *MockMessageRepository_Count_Call {
	_c.Call.Return(run)
	return _c
}

// Fetch provides a mock function for the type MockMessageRepository
func (_mock *MockMessageRepository) Fetch(ctx context.Context, r *model.ListMessagesRequest) ([]model.Message, error) {
	ret := _mock.Called(ctx, r)

	if len(ret) == 0 {
		panic("no return value specified for Fetch")
	}

	var r0 []model.Message
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *model.ListMessagesRequest) ([]model.Message, error)); ok {
		return returnFunc(ctx, r)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *model.ListMessagesRequest) []model.Message); ok {
		r0 = returnFunc(ctx, r)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Message)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *model.ListMessagesRequest) error); ok {
		r1 = returnFunc(ctx, r)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockMessageRepository_Fetch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Fetch'
type MockMessageRepository_Fetch_Call struct {
	*mock.Call
}

// Fetch is a helper method to define mock.On call
//   - ctx context.Context
//   - r *model.ListMessagesRequest
func (_e *MockMessageRepository_Expecter) Fetch(ctx interface{}, r interface{}) *MockMessageRepository_Fetch_Call {
	return &MockMessageRepository_Fetch_Call{Call: _e.mock.On("Fetch", ctx, r)}
}

func (_c *MockMessageRepository_Fetch_Call) Run(run func(ctx context.Context, r *model.ListMessagesRequest)) *MockMessageRepository_Fetch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *model.ListMessagesRequest
		if args[1] != nil {
			arg1 = args[1].(*model.ListMessagesRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockMessageRepository_Fetch_Call) Return(messages []model.Message, err error) *MockMessageRepository_Fetch_Call {
	_c.Call.Return(messages, err)
	return _c
}

func (_c *MockMessageRepository_Fetch_Call) RunAndReturn(run func(ctx context.Context, r *model.ListMessagesRequest) ([]model.Message, error)) *MockMessageRepository_Fetch_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type MockMessageRepository
func (_mock *MockMessageRepository) Update(ctx context.Context, msg *model.Message) (*model.Message, error) {
	ret := _mock.Called(ctx, msg)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 *model.Message
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *model.Message) (*model.Message, error)); ok {
		return returnFunc(ctx, msg)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *model.Message) *model.Message); ok {
		r0 = returnFunc(ctx, msg)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Message)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *model.Message) error); ok {
		r1 = returnFunc(ctx, msg)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockMessageRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockMessageRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - msg *model.Message
func (_e *MockMessageRepository_Expecter) Update(ctx interface{}, msg interface{}) *MockMessageRepository_Update_Call {
	return &MockMessageRepository_Update_Call{Call: _e.mock.On("Update", ctx, msg)}
}

func (_c *MockMessageRepository_Update_Call) Run(run func(ctx context.Context, msg *model.Message)) *MockMessageRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *model.Message
		if args[1] != nil {
			arg1 = args[1].(*model.Message)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockMessageRepository_Update_Call) Return(message *model.Message, err error) *MockMessageRepository_Update_Call {
	_c.Call.Return(message, err)
	return _c
}

func (_c *MockMessageRepository_Update_Call) RunAndReturn(run func(ctx context.Context, msg *model.Message) (*model.Message, error)) *MockMessageRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}
